name: Pipeline

on: [push]
env: 
#   CONTENT_PATH: ${{ github.workspace }}/test_directory
  TARGET_DIRECTORY: ${{ github.workspace }}/target_directory 
  ARTIFACT_NAME: Notebook   
jobs:
  Build:
    runs-on : ubuntu-18.04
    steps:
    -  uses: actions/checkout@v1
    -  name: Setup Python Env
       uses: actions/setup-python@v2
    -  name: Install requirements
       run: |
          pip install  --quiet --requirement requirement.txt
          pip install check-wheel-contents
    -  name: Building wheel file
       run: |
         python setup.py sdist bdist_wheel
         python -m pip install --upgrade pip
         ls
    -  name: Lint code
       run: |
         flake8  
    -  name: Run unit tests
       run: |
         python - m unitest  --verbose --failfast

    - run: cp -r dist ${{ env.TARGET_DIRECTORY }}
    - name: Publish Artifact Notebook
      uses: actions/upload-artifact@v2
      with:
         name: ${{ env.ARTIFACT_NAME }}
         path: ${{ env.TARGET_DIRECTORY }}

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1
        
#     - name: Login to DockerHub
#       uses: docker/login-action@v1
#       with:
#          username: ${{ secrets.DOCKER_HUB_USER }}
#          password: ${{ secrets.DOCKER_HUB_PASS }}
      
#     - name: Build and push
#       uses: docker/build-push-action@v2
#       with:
#           context: .
#           file: ./Dockerfile
#           pull: true
#           push: true
#           cache-from: type=registry,ref=adityareddy369/pythondemo          
#           cache-to: type=inline
#           tags: adityareddy369/pythondemo
#           build-args: PROFILE=nectar,ARG2=test
  DeployDev:
    name: Deploy to Dev 
    needs: [Build]
    runs-on: ubuntu-18.04
    environment: 
      name: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dowload Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.TARGET_DIRECTORY }}
      - name: Deploy
        run: |
          ls target_directory/
          -m pip install --upgrade pip
          pip install target_directory/hive-0.0.1-py3-none-any.whl
          echo I am deploying! 

  DeployStaging:
    name: Deploy to Staging 
    needs: [Build]
    runs-on: ubuntu-18.04
    environment: 
      name: Staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dowload Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.TARGET_DIRECTORY }}
      - name: Deploy
        run: echo I am deploying! 

#   DeployProd:
#     name: Deploy to Production 
#     needs: [DeployStaging]
#     runs-on: ubuntu-18.04
#     environment: 
#       name: Prod
      
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Dowload Build Artifact
#         uses: actions/download-artifact@v2
#         with:
#           name: ${{ env.ARTIFACT_NAME }}
#           path: ${{ env.TARGET_DIRECTORY }}
#       - name: Deploy
#         run: echo I am deploying! 
